#!/usr/bin/env node
// ============================================================
// web-factory · prebuild
// ------------------------------------------------------------
// Runs BEFORE `vite build`. From a single site.json it:
//   1. loads + validates the config (fails LOUD on bad input)
//   2. writes src/site.generated.js  (the runtime config object)
//   3. writes public/robots.txt + public/sitemap.xml (host-derived)
//   4. subsets Noto Sans SC → public/fonts/cjk.woff2 for exactly the
//      CJK glyphs this site uses (skipped gracefully if no CJK text)
//
// site.json path: env SITE_JSON, else ./site.json
// CJK source TTF: env NOTO_SC_TTF, else a small cache-download path.
// ============================================================

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { loadSiteConfig, collectCjkText } from './site-config.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const SITE_JSON = process.env.SITE_JSON || path.join(ROOT, 'site.json');
const SRC = path.join(ROOT, 'src');
const PUBLIC = path.join(ROOT, 'public');
const FONTS = path.join(PUBLIC, 'fonts');
const CJK_OUT = path.join(FONTS, 'cjk.woff2');

// Where to find / cache the source Noto Sans SC variable TTF.
// CI downloads it; locally a cached copy is reused.
const NOTO_SRC = process.env.NOTO_SC_TTF || path.join(os.tmpdir(), 'NotoSansSC-VF.ttf');
const NOTO_URL =
  process.env.NOTO_SC_URL ||
  'https://raw.githubusercontent.com/google/fonts/main/ofl/notosanssc/NotoSansSC%5Bwght%5D.ttf';

function log(...a) {
  console.log('[web-factory:prebuild]', ...a);
}

// ------------------------------------------------------------
function ensureNotoSource() {
  if (fs.existsSync(NOTO_SRC) && fs.statSync(NOTO_SRC).size > 100_000) {
    log(`Noto Sans SC source: ${NOTO_SRC} (cached)`);
    return NOTO_SRC;
  }
  // try to download once into the cache location
  log(`Noto Sans SC source not found; downloading from ${NOTO_URL}`);
  try {
    execFileSync('curl', ['-fsSL', '-o', NOTO_SRC, NOTO_URL], { stdio: 'inherit' });
  } catch {
    try {
      execFileSync('wget', ['-qO', NOTO_SRC, NOTO_URL], { stdio: 'inherit' });
    } catch {
      throw new Error(
        `could not fetch Noto Sans SC source. Set NOTO_SC_TTF=/path/to/NotoSansSC-VF.ttf ` +
          `or NOTO_SC_URL to a reachable TTF.`
      );
    }
  }
  if (!fs.existsSync(NOTO_SRC) || fs.statSync(NOTO_SRC).size < 100_000) {
    throw new Error(`downloaded Noto Sans SC source looks invalid (${NOTO_SRC})`);
  }
  return NOTO_SRC;
}

function hasPyftsubset() {
  try {
    execFileSync('pyftsubset', ['--help'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function subsetCjk(cfg) {
  const text = collectCjkText(cfg);
  if (!text) {
    log('no CJK text in site.json → skipping CJK subset (en-only site).');
    // remove any stale subset so the @font-face 404s soft (font-display:swap)
    if (fs.existsSync(CJK_OUT)) fs.rmSync(CJK_OUT);
    return { subset: false, glyphs: 0 };
  }
  if (!hasPyftsubset()) {
    throw new Error(
      `site.json contains CJK text but pyftsubset is not installed. ` +
        `Install it: pip install fonttools brotli`
    );
  }
  const src = ensureNotoSource();
  fs.mkdirSync(FONTS, { recursive: true });

  // keep the wght axis so 400..700 weights all render from one file
  execFileSync(
    'pyftsubset',
    [
      src,
      `--text=${text}`,
      `--output-file=${CJK_OUT}`,
      '--flavor=woff2',
      '--layout-features=*',
      '--glyph-names',
      '--symbol-cmap',
      '--notdef-outline',
      '--recalc-bounds',
      '--recalc-timestamp',
      '--drop-tables=',
      '--name-IDs=*',
      '--name-legacy',
      '--name-languages=*',
      '--retain-gids=false',
      // NOTE: pyftsubset keeps the fvar/gvar weight axis by default (we do
      // not pass --instance*, so the wght axis 100..900 survives the subset).
    ],
    { stdio: 'inherit' }
  );
  const kb = (fs.statSync(CJK_OUT).size / 1024).toFixed(1);
  log(`CJK subset → ${path.relative(ROOT, CJK_OUT)} (${text.length} glyphs, ${kb} KB)`);
  return { subset: true, glyphs: text.length };
}

// ------------------------------------------------------------
function writeRuntimeConfig(cfg) {
  fs.mkdirSync(SRC, { recursive: true });
  const banner =
    '// AUTO-GENERATED by scripts/prebuild.js from site.json — do not edit by hand.\n';
  const body = `export const SITE = ${JSON.stringify(cfg, null, 2)};\n`;
  fs.writeFileSync(path.join(SRC, 'site.generated.js'), banner + body);
  log(`runtime config → src/site.generated.js`);
}

function writeSeoFiles(cfg) {
  fs.mkdirSync(PUBLIC, { recursive: true });
  const origin = cfg.origin || '';
  // robots.txt
  const robots = origin
    ? `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`
    : `User-agent: *\nAllow: /\n`;
  fs.writeFileSync(path.join(PUBLIC, 'robots.txt'), robots);

  // sitemap.xml (single-page site)
  const today = new Date().toISOString().slice(0, 10);
  const loc = origin ? `${origin}/` : '/';
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`;
  fs.writeFileSync(path.join(PUBLIC, 'sitemap.xml'), sitemap);
  log(`SEO → public/robots.txt + public/sitemap.xml (origin: ${origin || '(none)'})`);
}

// Branded 404 — dark, one line, link home. Vite copies public/ into
// dist/ verbatim, and GitHub Pages serves 404.html automatically.
function write404(cfg) {
  fs.mkdirSync(PUBLIC, { recursive: true });
  const accent = cfg.accent[0];
  const en = cfg.lang.primary === 'en';
  const line = en ? 'This page does not exist.' : '这个页面不存在。';
  const back = en ? `Back to ${cfg.name}` : `返回 ${cfg.name}`;
  const html = `<!doctype html>
<html lang="${en ? 'en' : 'zh-CN'}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="robots" content="noindex" />
<title>404 · ${cfg.name}</title>
<style>
  @font-face {
    font-family: "Space Grotesk";
    font-style: normal;
    font-weight: 300 700;
    font-display: swap;
    src: url("/fonts/space-grotesk-latin-var.woff2") format("woff2");
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { height: 100%; }
  body {
    background: #06070c;
    color: #eceef5;
    font-family: "Space Grotesk", -apple-system, BlinkMacSystemFont, "PingFang SC", system-ui, sans-serif;
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    background-image: radial-gradient(58% 50% at 70% 20%, ${accent}1f, transparent 62%);
  }
  main { padding: 2rem; }
  .code {
    font-size: clamp(4rem, 16vw, 9rem);
    font-weight: 600;
    letter-spacing: -0.04em;
    line-height: 1;
    color: ${accent};
  }
  p { margin-top: 1rem; color: #8d93a6; font-size: 1.05rem; }
  a {
    display: inline-block;
    margin-top: 2rem;
    color: #06070c;
    background: ${accent};
    font-weight: 600;
    text-decoration: none;
    padding: 0.7rem 1.4rem;
    border-radius: 999px;
    transition: transform 0.3s cubic-bezier(0.32, 0.72, 0, 1);
  }
  a:hover { transform: translateY(-2px); }
  a:active { transform: scale(0.98); }
  a:focus-visible { outline: 2px solid #fff; outline-offset: 3px; }
</style>
</head>
<body>
<main>
  <div class="code">404</div>
  <p>${line}</p>
  <a href="/">${back}</a>
</main>
</body>
</html>
`;
  fs.writeFileSync(path.join(PUBLIC, '404.html'), html);
  log('404 → public/404.html');
}

// ------------------------------------------------------------
function main() {
  log(`SITE_JSON = ${SITE_JSON}`);
  const cfg = loadSiteConfig(SITE_JSON); // throws SiteConfigError on bad input
  log(`building site for "${cfg.name}" → ${cfg.host || '(no host)'}`);
  writeRuntimeConfig(cfg);
  writeSeoFiles(cfg);
  write404(cfg);
  subsetCjk(cfg);
  log('prebuild complete.');
}

try {
  main();
} catch (err) {
  console.error('\n\x1b[31m[web-factory] BUILD FAILED\x1b[0m');
  console.error(err.message || err);
  process.exit(1);
}
